add new streams for Voice Calls, Voice Call Recordings, and Voice Call Events
Pathlight/tap-gorgias pull request #10
Opened 2024-07-24 20:39 UTC by cscott20

https://linear.app/pathlight/issue/CI-1115/gorgias-tap-update-to-include-voice-calls-voice-call-events-and-voice

2024-07-24 21:41 UTC, vorpal56 requested changes
all properties can be null which means there's no primary key in the table. some of these fields shouldn't be null too, so should check those

2024-07-24 21:41 UTC, vorpal56 commented on tap_gorgias/schemas/voice_calls.json
> +      "description": "ID of the voice call."
this cannot be null. otherwise there's no primary key

2024-07-24 21:41 UTC, vorpal56 commented on tap_gorgias/schemas/voice_call_recordings.json
> +    },
same here. the id property is the primary key and cannot be null. I would also assume that call_id should never be null

2024-07-24 21:41 UTC, vorpal56 commented on tap_gorgias/schemas/voice_call_events.json
> +    },
same here

2024-07-24 21:41 UTC, vorpal56 commented on tap_gorgias/schemas/voice_call_events.json
> +      "description": "The voice call event type."
a voice event should have an event type that's not null.

2024-07-24 21:41 UTC, vorpal56 commented on tap_gorgias/schemas/voice_call_events.json
> +      "description": "When the event was created."
all of these should probably not be null either, right?

2024-07-25 15:14 UTC, cscott20 commented
Hm, interesting observation @vorpal56 . If you take a look at the other schemas, all of them have all fields as nullable, which is why I followed that pattern here.

2024-07-25 15:17 UTC, cscott20 commented
Check out this maintained open source repo, you can see here as well that all fields are nullable on the schema including ID.
https://github.com/singer-io/tap-intercom/blob/master/tap_intercom/schemas/conversations.json

2024-07-25 17:09 UTC, vorpal56 commented on tap_gorgias/streams.py
> +    url = '/api/phone/voice-call-events'
voice_call_events are ascending order, so I don't think we can take advantage of any bookmarks/config start date? maybe we could use the cursor as a bookmark? I'm fine with how it is though. you mind including a comment that it's in ascending?

2024-07-25 17:09 UTC, vorpal56 commented on tap_gorgias/streams.py
> +    url = '/api/phone/voice-call-recordings'
this is ordered in descending, meaning we can take advantage of the config/bookmark date to stop fetching there's a record time stamp older than the sync date.

2024-07-25 17:09 UTC, vorpal56 commented on tap_gorgias/streams.py
> +    url = '/api/phone/voice-calls'
also ordered in descending, can use bookmarks/config start date

2024-07-25 18:37 UTC, cscott20 commented
@vorpal56 Lmk if those changes address your concerns
Thanks for authoring the commit to address your initial asks!

2024-07-25 18:43 UTC, vorpal56 approved these changes

2024-07-25 19:28 UTC, merged